const lifts = require('../lifts');

lifts('3cime', 'html', {
  'Tre Cime': 'closed',
  Stiergarten: 'closed',
  'Heinrich Harrer': 'closed',
  Porzen: 'closed',
  'Croda Rossa': 'closed',
  Hasenkoepfl: 'closed',
  Brugger: 'closed',
  Raut: 'closed',
  Wiese: 'closed',
  Uebungslift: 'closed',
  Mittelstation: 'closed',
  'Versciaco - Monte Elmo': 'closed',
  Hawaii: 'closed',
  Signaue: 'closed',
  'Helmjet Sesto': 'closed',
  'Bus - Ski Area Val Comelico - Signaue': 'closed',
  'Bus - Ski Area Val Comelico - Val Grande': 'closed',
  'Treno Versciaco - Perca': 'closed',
  'Monte Baranci': 'closed',
  Erschbaum: 'closed',
  Doris: 'closed',
  Untertal: 'closed',
  Laerchen: 'closed',
  Trenker: 'closed',
  Rienza: 'closed',
  'Waldheim I': 'closed',
  'Waldheim II': 'closed',
  'Kreuzberg II': 'open',
  'Kreuzberg I': 'open',
  Kameriot: 'closed',
  Sonnleiten: 'closed',
  Cenerentola: 'closed',
  "Col d'la Tenda": 'closed',
});
