const lifts = require('../lifts');

lifts('alta-badia', 'html', {
  'Col Alto': 'closed',
  'Braia Fraida': 'closed',
  'Capanna Nera': 'closed',
  'Pralongiá': 'closed',
  'Pralongiá I': 'closed',
  'Pralongiá II': 'closed',
  'Crep de Mont': 'closed',
  'Boé': 'closed',
  'Vallon': 'closed',
  'Costoratta': 'closed',
  "Costes da l'Ega": 'closed',
  'Arlara': 'closed',
  'Pre Ciablun': 'closed',
  'Incisa': 'closed',
  'Cherz 1': 'closed',
  'Cherz 2': 'closed',
  'La Vizza': 'closed',
  'Masarei': 'closed',
  'Abrusé': 'closed',
  'Borest': 'closed',
  'Sodlisia': 'closed',
  'Pezzei': 'closed',
  'Plans': 'closed',
  'Frara': 'closed',
  'Col Pradat': 'closed',
  'Colfosco': 'closed',
  'Forcelles': 'closed',
  'Stella Alpina': 'closed',
  'Val Setus': 'closed',
  'Piz La Ila': 'closed',
  'Ferata Gran Risa': 'closed',
  'Pre dai Corf': 'closed',
  'Bamby': 'closed',
  'Roby': 'closed',
  'La Rüa': 'closed',
  'Colz': 'closed',
  'Doninz': 'closed',
  'Gardenaccia': 'closed',
  "Col d'Altin": 'closed',
  'Piz Sorega': 'closed',
  'Codes': 'closed',
  'La Brancia': 'closed',
  'Biok': 'closed',
  'Ciampai': 'closed',
  'La Para': 'closed',
  'La Fraina': 'closed',
  'Armentarola': 'closed',
  'Baby La Crusc': 'closed',
  'La Crusc 1': 'closed',
  'La Crusc 2': 'closed',
  'Pradüc': 'closed',
  'Sponata': 'closed',
  'Sompunt/ Sponata - Piculin': 'closed',
  'Piculin - Sompunt/ Sponata': 'closed',
  'Falzarego - Lagazuoi': 'closed'
});
