const lifts = require('../lifts');

lifts('arabba', 'html', {
  'Porta Vescovo': 'closed',
  Pescoi: 'closed',
  'Forcella Europa': 'closed',
  Portados: 'closed',
  Carpazza: 'closed',
  'Sass de la Vegla': 'closed',
  Mesola: 'closed',
  Antercrëp: 'closed',
  Lezuo: 'closed',
  Maria: 'closed',
  Fodom: 'closed',
  Alpenrose: 'closed',
  Burz: 'closed',
  'Le Pale': 'closed',
  Campolongo: 'closed',
  'Arabba Fly': 'closed',
  'Cherz 1': 'closed',
  'Cherz 2': 'closed',
  'La Vizza': 'closed',
  Masarei: 'closed',
  Incisa: 'closed',
  'Malga - Banc': 'closed',
  'Banc - Serauta': 'closed',
  'Serauta- P.Rocca': 'closed',
  Padon: 'closed',
  'Campo Scuola': 'closed',
});
