const lifts = require('../lifts');

lifts('big-sky', 'html', {
  'Bear Back Poma': 'open',
  'Bear Basin Carpet': 'open',
  'Beehive Basin Carpet': 'open',
  'Cabin 3': 'closed',
  'Cascade 3': 'closed',
  'Challenger 3': 'open',
  'Dakota 3': 'closed',
  'Derringer 4': 'open',
  'Explorer 2': 'open',
  'Headwaters 2': 'closed',
  'Highlands 3': 'closed',
  'Homer Poma': 'closed',
  'Iron Horse 4': 'closed',
  'Jayhawk 3': 'closed',
  'Lewis and Clark 4': 'open',
  'Little Thunder 2': 'closed',
  'Lone Moose 3': 'closed',
  'Lone Peak Tram': 'scheduled',
  'Lone Tree 4': 'closed',
  'Middle Basin Carpet': 'open',
  'Pea Shooter Carpet': 'open',
  'Pony Express 3': 'closed',
  'Powder Seeker 6': 'open',
  'Pull-Up Tow': 'closed',
  'Ramcharger 8': 'open',
  'Sacajawea 3': 'closed',
  'Shedhorn 4': 'closed',
  'Six Shooter 6': 'closed',
  'Skiwee Carpet': 'open',
  'Small Fry Carpet': 'open',
  'Southern Comfort 4': 'closed',
  'Spanish Peaks Carpet': 'open',
  'Spanish Peaks Carpet 2': 'open',
  'Stagecoach 2': 'closed',
  'Swift Current 6': 'open',
  'Thunder Wolf 4': 'open',
  'Tweener Poma': 'closed',
  'White Otter 2': 'open'
});
