const lifts = require('../lifts');

lifts('breck', 'html', {
  'A Chair': 'closed',
  'Beaver Run Superchair': 'closed',
  'C Chair': 'closed',
  'Camelback Platter': 'closed',
  'Castle Carpet 1': 'closed',
  'Castle Carpet 2': 'closed',
  'Chair 5': 'closed',
  'Chair 6': 'closed',
  'Colorado Superchair': 'closed',
  'E Chair': 'closed',
  'El Dorado Carpet C': 'closed',
  'El Dorado Carpet D': 'closed',
  'El Dorado Tow': 'closed',
  'Falcon Superchair': 'closed',
  'Gondola': 'closed',
  'Imperial Express SuperChair': 'closed',
  'Independence SuperChair': 'closed',
  'Kensho Superchair': 'closed',
  'Kids Carpet 3': 'closed',
  'Kids Carpet 4': 'closed',
  'Mercury Superchair': 'closed',
  'Peak 8 SuperConnect': 'closed',
  'Quicksilver Super6': 'closed',
  'Rip\'s Ride': 'closed',
  'Rocky Mountain Superchair': 'closed',
  'Snowflake': 'closed',
  'T-Bar': 'closed',
  'Trygve\'s Carpet': 'closed',
  'Trygve\'s Platter': 'closed',
  'Village Carpet A': 'closed',
  'Village Carpet B': 'closed',
  'Village Carpet C': 'closed',
  'Village Carpet D': 'closed',
  'Zendo Chair': 'closed'
});
