const lifts = require('../lifts');

lifts('civetta', 'html', {
  'Alleghe/Piani di Pezzè': 'closed',
  'Piani di Pezzè/Col dei Baldi': 'closed',
  'Baby - Piani di Pezzè': 'closed',
  Pelmo: 'closed',
  'Col Fioret': 'closed',
  Belamont: 'closed',
  'Campo Scuola Mariaz': 'closed',
  'Malga Ciapela-Alleghe': 'closed',
  'Alleghe-Malga Ciapela': 'closed',
  'Pecol/Pian del Crep': 'closed',
  'Delle Coste': 'closed',
  Cristelin: 'closed',
  'Valgranda-Col de la Grava': 'closed',
  Campetto: 'closed',
  Palma: 'closed',
  'Casot di Pecol': 'closed',
  'Casot di Pecol-Col de la Grava': 'closed',
  Pioda: 'closed',
  Palafavera: 'closed',
  Pelmetto: 'closed',
  'Pescul/Fertazza': 'closed',
  Fertazza: 'closed',
  'Lastiè (imp. con curva)': 'closed',
  'Rio Canedo': 'closed',
  'Santa Fosca': 'closed',
  'Pescul-Fedare': 'closed',
  'Fedare-Pescul': 'closed',
});
