const lifts = require('../lifts');

lifts('courchevel', 'html', {
  "Rocher De L'ombre": 'scheduled',
  Sources: 'scheduled',
  Verdons: 'scheduled',
  Biollay: 'scheduled',
  Pralong: 'scheduled',
  'Aiguille Du Fruit': 'scheduled',
  Altiport: 'scheduled',
  Ferme: 'scheduled',
  Cospillot: 'scheduled',
  'Jardin Alpin': 'scheduled',
  Etoiles: 'scheduled',
  'Golf 1850 N°1': 'scheduled',
  Bellecôte: 'scheduled',
  'Golf 1850 N°2': 'scheduled',
  'Golf 1850 N°3': 'scheduled',
  Chanrossa: 'scheduled',
  'Roc Merlet': 'scheduled',
  'Pyramides 1': 'scheduled',
  'Pyramides 2': 'scheduled',
  'Dou Des Lanches': 'scheduled',
  'Bouc Blanc': 'scheduled',
  Tania: 'scheduled',
  'Gros Murger': 'closed',
  'Mon Tania': 'scheduled',
  'Ours Brun': 'scheduled',
  'Stade Tania': 'scheduled',
  Grizzly: 'scheduled',
  Chenus: 'scheduled',
  Coqs: 'closed',
  'Loze a': 'scheduled',
  Plantrey: 'scheduled',
  Forêt: 'closed',
  Epicéa: 'scheduled',
  Praz: 'open',
  Grangettes: 'open',
  Tovets: 'scheduled',
  Roys: 'scheduled',
  'Loze B': 'scheduled',
  Envolée: 'scheduled',
  'Grandes Combes': 'scheduled',
  "Jardin D'enfants": 'scheduled',
  Saulire: 'closed',
  Vizelle: 'scheduled',
  Suisses: 'scheduled',
  Marmottes: 'scheduled',
  Chapelets: 'closed',
  Signal: 'scheduled',
  'Roc Mugnier': 'scheduled',
  'Petite Bosse': 'scheduled',
  Ariondaz: 'scheduled',
  Grange: 'scheduled',
  Belvédère: 'scheduled',
  Mickey: 'scheduled',
  'Petit Moriond': 'scheduled',
  Mine: 'scheduled',
  Sheriff: 'scheduled',
});
