const lifts = require('../lifts');

lifts('heavenly', 'html', {
  'Aerial Tram': 'closed',
  'Bear Cave Carpet': 'closed',
  'Big Easy': 'closed',
  'Boulder': 'closed',
  'Boulder Carpet': 'closed',
  'Canyon': 'closed',
  'Comet': 'closed',
  'Dipper': 'closed',
  'DMZ Carpet': 'closed',
  'Enchanted Carpet': 'closed',
  'First Ride': 'closed',
  'Galaxy': 'closed',
  'Gondola': 'closed',
  'Groove': 'closed',
  'Gunbarrel': 'closed',
  'Mott': 'closed',
  'North Bowl': 'closed',
  'Olympic': 'closed',
  'Patsy\'s': 'closed',
  'Powderbowl': 'closed',
  'Sky': 'closed',
  'Stagecoach': 'closed',
  'Mitey Mite 1': 'closed',
  'Mitey Mite 2': 'closed',
  'Pioneer Mitey-Mite': 'closed',
  'Red Fir Mitey Mite': 'closed',
  'Tamarack': 'closed',
  'Tubing Lift': 'closed',
  'World Cup': 'closed'
});
