const lifts = require('../lifts');

lifts('heavenly', 'html', {
  'Aerial Tram': 'closed',
  'Bear Cave': 'closed',
  'Big Easy': 'closed',
  Boulder: 'closed',
  Canyon: 'closed',
  Comet: 'closed',
  Dipper: 'closed',
  DMZ: 'closed',
  'Enchanted Forest': 'closed',
  'First Ride': 'closed',
  Galaxy: 'closed',
  Gondola: 'closed',
  Groove: 'closed',
  Gunbarrel: 'closed',
  Mott: 'closed',
  'North Bowl': 'closed',
  Olympic: 'closed',
  "Patsy's": 'closed',
  Pioneer: 'closed',
  Powderbowl: 'closed',
  'Red Fir': 'closed',
  Sky: 'closed',
  Stagecoach: 'closed',
  Tamarack: 'closed',
  'Tube Lift': 'closed',
  'World Cup': 'closed'
});
