const lifts = require('../lifts');

lifts('hochfuegen', 'html', {
  '8er Jet Hochfügen': 'open',
  '6er KSB Holzalm': 'open',
  '8er EUB Zillertal Shuttle': 'open',
  '6er Sesselbahn Waidoffen': 'open',
  '2er Pfaffenbühel': 'closed',
  'Pfaffenbühel II': 'closed',
  'Pfaffenbühel III': 'open',
  'Lamarklift I': 'open',
  'Lamarklift II': 'open',
  'Förderband Lamark': 'open',
  'Lamarklift IV': 'open',
  'Achteralm': 'open',
  'Hochzillertal I': 'closed',
  'Hochzillertal II': 'closed',
  'Hochzillertal III': 'open',
  'Schnee-Express': 'open',
  'Sonnenjet': 'open',
  'Neuhüttenbahn': 'closed',
  'Wimbachexpress': 'open',
  'Wedelexpress': 'open',
  'Topjet': 'open',
  'Öfelerbahn': 'closed',
  'Panoramalift': 'closed',
  'Hirschbichllift': 'open',
  'Parklift': 'open',
  'Zirbenlift I': 'open',
  'Zirbenlift II': 'closed',
  'Marendalmlift I': 'closed',
  'Marendalmlift II': 'closed',
  'Übungslift I': 'closed',
  'Übungslift II': 'closed',
  'Kindergartenlift Marend': 'closed',
  'Übungslift-Telecorde I': 'closed',
  'Übungslift Telecorde II': 'closed',
  'Übungslift-Telecorde III': 'closed',
  'Kristall- Express': 'open',
  'Mizunbahn': 'closed'
});
