const lifts = require('../lifts');

lifts('kitzbuehel', 'html', {
  'A1 Hahnenkammbahn': 'open',
  'A2 Ganslern': 'closed',
  'A3 Walde': 'closed',
  'A4 Fleckalmbahn': 'open',
  'A5 Rasmusleiten': 'closed',
  'A6 Märchenwald': 'closed',
  'A7 Starthaus': 'closed',
  'A8 Ministreif': 'closed',
  'A9 Mocking': 'closed',
  'B1 Hornbahn I': 'open',
  'B2 Hornbahn II': 'open',
  'B3 Horngipfelbahn': 'open',
  'B4 Raintal': 'closed',
  'B5 Brunelle': 'closed',
  'B6 Alpenhaus': 'closed',
  'B7 Hornköpfl': 'closed',
  'B8 Sun Kid Horn': 'closed',
  'B9 Eggl': 'closed',
  'B10 Trattalmmulde': 'closed',
  'C1 Steinbergkogel': 'closed',
  'C2 Ehrenbachhöhe': 'closed',
  'C3 Jufen': 'closed',
  'C4 Sonnenrast': 'closed',
  'D1 Silberstube': 'closed',
  'D2 Brunn': 'closed',
  'D3 Pengelstein II': 'closed',
  'D4 Usterkar': 'closed',
  'D5 Pengelstein I': 'closed',
  'D6 Hieslegg': 'closed',
  'D7 Kasereck': 'closed',
  'D8 Hochsaukaser': 'closed',
  'D9 3S-Bahn': 'closed',
  'D10 Übungslift Aschau': 'closed',
  'D11 Sun Kid Aschau': 'closed',
  'E1 Maierlbahn': 'closed',
  'E2 Ochsalm': 'closed',
  'E5 Übungslift Reith': 'closed',
  'E6 Sun Kid Reith': 'closed',
  'E7 Schatzerlift (Übungslift)': 'closed',
  'E8 Gaisberg': 'open',
  'F1 Wagstättbahn': 'closed',
  'F3 Hausleiten': 'closed',
  'F5 Talsen': 'closed',
  'F6 Bärenbadkogel I': 'closed',
  'F7 Bärenbadkogel II': 'closed',
  'F8 Gauxjoch': 'closed',
  'F9 Trattenbach': 'closed',
  'G1 Resterhöhe': 'closed',
  'G2 Pass Thurn': 'closed',
  'G4 Resterkogel': 'closed',
  'G5 Hanglalm': 'closed',
  'G7 Hartkaser': 'closed',
  'G8 Zweitausender': 'closed',
  'G9 Panoramabahn I': 'open',
  'G10 Panoramabahn II': 'open',
  'G11 Sun Kid Resterhöhe': 'closed',
  'H1 Bichlalm': 'open',
  'Schneekatze': 'closed',
});
