import lifts from '../lifts/index.js';

lifts('laplagne', 'html', {
  'Télémetro': 'open',
  'Bécoin': 'open',
  Golf: 'open',
  'Plagne 1800': 'open',
  'Aime La Plagne': 'open',
  Cretes: 'closed',
  Dromadaire: 'open',
  Praconduit: 'open',
  Stade: 'open',
  'Funiplagne Grande Rochette': 'open',
  'Télébus': 'open',
  Bergerie: 'open',
  Colorado: 'open',
  'Lovatière': 'closed',
  Boulevard: 'open',
  'Mélèzes': 'open',
  Aollets: 'open',
  Biquet: 'open',
  Chevrette: 'open',
  'Dou Du Praz.': 'open',
  France: 'open',
  Indiens: 'open',
  Solu: 'open',
  'Belle Plagne.': 'open',
  'Roche De Mio 1': 'open',
  'Roche De Mio 2': 'closed',
  Arpette: 'open',
  Blanchets: 'open',
  Carella: 'closed',
  Colosses: 'open',
  Inversens: 'closed',
  Quillis: 'open',
  'Col De Forcle': 'closed',
  Tyrolien: 'open',
  Ange: 'open',
  'Belle Plagne': 'open',
  Ourson: 'open',
  'Plateau De Carella': 'closed',
  'Glaciers 1 - Retour Roche De Mio': 'closed',
  'Glaciers 1 - Vers Live3000': 'closed',
  'Glaciers 2': 'closed',
  'Chalet De Bellecôte': 'closed',
  Champagny: 'open',
  Borseliers: 'open',
  Rossa: 'open',
  'Verdons Sud': 'closed',
  Aiglon: 'open',
  'Borseliers Iii': 'open',
  Eterlou: 'open',
  'Vanoise Express Montchavin': 'open',
  'Vanoise Express Peisey': 'open',
  Coches: 'open',
  'Lac Noir.': 'open',
  Telebuffette: 'open',
  Bijolin: 'open',
  Crozats: 'open',
  Montchavin: 'open',
  'Pierres Blanches.': 'open',
  'Plan Bois.': 'open',
  Bauches: 'open',
  'Dos Rond.': 'open',
  Salla: 'open',
  Ecureuils: 'open',
  'Petit Sauget': 'open',
  'Plan Leschaux': 'open',
  'Petits Loups': 'open',
  Patinoire: 'open',
  Replat: 'open',
  'Sucette De Montchavin': 'open',
  Montalbert: 'open',
  Envers: 'open',
  Roche: 'open',
  Adrets: 'open',
  Gentil: 'open',
  Grangette: 'closed',
  Grenouilles: 'scheduled'
});
