const lifts = require('../lifts');

lifts('laplagne', 'html', {
  'TC BELLECOTE': 'closed',
  'TS CHALET BELLECOTE': 'closed',
  'TS GLACIER': 'closed',
  'TS TRAVERSEE': 'closed',
  'TC CHAMPAGNY': 'scheduled',
  'TSD ROSSA': 'scheduled',
  'TSD BORSELIERS': 'scheduled',
  'TSD VERDONS SUD': 'closed',
  'FIL MARMOTTONS': 'scheduled',
  'FIL NEIGE RAFFORT': 'closed',
  'TK BERGERIE': 'scheduled',
  'TK BORSELIERS 3': 'scheduled',
  'TK ETERLOU': 'scheduled',
  'FUNIPLAGNE G.ROCHE': 'closed',
  'TC TELEBUS': 'scheduled',
  'TSD BERGERIE': 'scheduled',
  'TSD COLORADO': 'scheduled',
  'TS BOULEVARD': 'scheduled',
  'TS MELEZES': 'scheduled',
  'TS VERDONS NORD': 'closed',
  'FIL NEIGE JARDIN': 'scheduled',
  'FIL NEIGE MICKEY': 'scheduled',
  'TELEBABY': 'scheduled',
  'TELECORDE SOLU': 'scheduled',
  'TK AOLLETS': 'closed',
  'TK BIQUET': 'scheduled',
  'TK CHEVRETTE': 'scheduled',
  'TK FRANCE': 'scheduled',
  'TSD MONTALBERT': 'scheduled',
  'TS ADRETS': 'scheduled',
  'TS FORNELET': 'scheduled',
  'FIL NEIGE CHAILLET': 'scheduled',
  'FIL NEIGE PANDA': 'scheduled',
  'TK FORNELET 2': 'closed',
  'TK GENTIL': 'scheduled',
  'TK GRANGETTE': 'closed',
  'TK GRENOUILLES': 'scheduled',
  'TK MONTALBERT': 'scheduled',
  'TC BELLE PLAGNE': 'open',
  'TC ROCHE DE MIO': 'closed',
  'TSD ARPETTE': 'scheduled',
  'TSD BLANCHETS': 'scheduled',
  'TSD CARELLA': 'closed',
  'TSD COLOSSES': 'scheduled',
  'TS BELLE PLAGNE': 'scheduled',
  'TS INVERSENS': 'closed',
  'TS QUILLIS': 'scheduled',
  'FIL NEIGE CARAMEL': 'scheduled',
  'FIL NEIGE CROETS': 'scheduled',
  'FIL NEIGE ILE ENFANTS': 'scheduled',
  'FIL NEIGE JARDIN ENFANTS': 'scheduled',
  'FIL NEIGE SUCRE ORGE': 'scheduled',
  'TELECORDE PLATEAU': 'closed',
  'TK TYROLIEN': 'scheduled',
  'TK BELLE PLAGNE': 'scheduled',
  'TK COL DE FORCLE 1': 'closed',
  'TK COL DE FORCLE 2': 'closed',
  'TK DOU DU PRAZ': 'scheduled',
  'TAPIS OURSON': 'scheduled',
  'TPH TELEMETRO': 'open',
  'TSD BECOIN': 'closed',
  'TSD ROCHE': 'scheduled',
  'TS GOLF': 'scheduled',
  'TS PLAGNE 1800': 'scheduled',
  'FIL NEIGE LA ROCHE': 'scheduled',
  'FIL NEIGE LUTINS': 'scheduled',
  'FIL NEIGE MINICLUB': 'scheduled',
  'TK AIME LA PLAGNE': 'scheduled',
  'TK CRETES': 'closed',
  'TK DROMADAIRE': 'scheduled',
  'TK PONEY': 'scheduled',
  'TK PRACONDUIT': 'scheduled',
  'TK STADES': 'scheduled',
  'PLAGNE > ARCS': 'scheduled',
  'CHAMP > PLA-BELLEC': 'scheduled',
  'CHAMP>PLA/VERDONS': 'closed',
  'LA PLAGNE > MTALBE': 'scheduled',
  'LA PLAGNE > MTCHAV': 'scheduled',
  'LA PLAGNE> P B': 'scheduled',
  'LA PLAGNE>CHAMP': 'scheduled',
  'MTALBERT > LA PLAG': 'scheduled',
  'MTCHAVIN > LA PLAG': 'scheduled',
  'PLA> CHAMP/VERD': 'closed',
  'SECTEUR GLACIER': 'closed',
  'TPH VANOISE EXPRESS': 'scheduled',
  'TC COCHES': 'scheduled',
  'TC LAC NOIR': 'scheduled',
  'TC TELEBUFFETTE': 'scheduled',
  'TS SALLA': 'scheduled',
  'TSD BIJOLIN': 'scheduled',
  'TSD MONTCHAVIN': 'scheduled',
  'TSD PIERRES BLANCHES': 'scheduled',
  'TSD PLAN BOIS': 'scheduled',
  'TS BAUCHES': 'scheduled',
  'TS CARROLEY': 'scheduled',
  'TS CROZATS': 'closed',
  'TS DOS ROND': 'scheduled',
  'FIL NEIGE BABY': 'scheduled',
  'FIL NEIGE PIROUETTE': 'scheduled',
  'FIL NEIGE PLAN BOIS': 'scheduled',
  'TELECORDE PATINOIRE': 'scheduled',
  'TELECORDE REPLAT': 'scheduled',
  'TELECORDE SUCETTE': 'scheduled',
  'TK MTCHAVIN': 'closed',
  'TK PETIT SAUGET': 'scheduled',
  'TK PLAN BOIS': 'scheduled',
  'TK PLAN LESCHAUX': 'scheduled',
  'CHAMPAGNY': 'scheduled',
  'LES COCHES': 'scheduled',
  'MONTALBERT': 'scheduled',
  'MONTCHAVIN': 'scheduled'
});
