const lifts = require('../lifts');

lifts('laplagne', 'html', {
  'Aime La Plagne': 'scheduled',
  Becoin: 'scheduled',
  Cretes: 'closed',
  Dromadaire: 'closed',
  Envers: 'scheduled',
  Golf: 'scheduled',
  'Plagne 1800': 'scheduled',
  Praconduit: 'scheduled',
  Roche: 'scheduled',
  Stade: 'scheduled',
  Telemetro: 'open',
  Aollets: 'scheduled',
  Bergerie: 'scheduled',
  Biquet: 'scheduled',
  Boulevard: 'scheduled',
  Chevrette: 'scheduled',
  Colorado: 'scheduled',
  'Dou Du Praz.': 'scheduled',
  France: 'scheduled',
  'Funiplagne Grande Rochette': 'scheduled',
  Melezes: 'scheduled',
  Solu: 'scheduled',
  Telebus: 'open',
  Lovatiere: 'scheduled',
  Indiens: 'scheduled',
  Ange: 'scheduled',
  Arpette: 'scheduled',
  'Belle Plagne.': 'open',
  'Belle Plagne..': 'scheduled',
  Blanchets: 'scheduled',
  Carella: 'scheduled',
  'Col De Forcle I': 'scheduled',
  Colosses: 'scheduled',
  Inversens: 'scheduled',
  Ourson: 'scheduled',
  'Plateau De Carella': 'scheduled',
  Quillis: 'scheduled',
  'Roche De Mio': 'scheduled',
  Tyrolien: 'scheduled',
  Bellecote: 'scheduled',
  'Chalet De Bellecote': 'scheduled',
  Glacier: 'closed',
  Traversee: 'scheduled',
  Aiglon: 'scheduled',
  'Borseliers Iii': 'scheduled',
  Borseliers: 'scheduled',
  Champagny: 'scheduled',
  Eterlou: 'scheduled',
  Rossa: 'scheduled',
  'Verdons Sud': 'scheduled',
  Bauches: 'scheduled',
  Bijolin: 'scheduled',
  Coches: 'scheduled',
  Crozats: 'scheduled',
  'Dos Rond.': 'scheduled',
  Ecureuils: 'scheduled',
  'Lac Noir.': 'scheduled',
  Montchavin: 'scheduled',
  Patinoire: 'scheduled',
  'Petit Sauget': 'scheduled',
  'Petits Loups': 'scheduled',
  'Pierres Blanches.': 'scheduled',
  'Plan Bois.': 'scheduled',
  'Plan Leschaux': 'closed',
  Replat: 'scheduled',
  Salla: 'closed',
  'Sucette De Montchavin': 'scheduled',
  Telebuffette: 'scheduled',
  'Vanoise Express': 'scheduled',
  Adrets: 'scheduled',
  Gentil: 'closed',
  Grangette: 'closed',
  Grenouilles: 'scheduled',
  Montalbert: 'scheduled',
});
