const lifts = require('../lifts');

lifts('larosiere', 'html', {
  'TS ECUDETS': 'closed',
  'TSD ROCHES NOIRES': 'closed',
  'TSD LES EUCHERTS': 'closed',
  'TSD PLAN DU REPOS': 'closed',
  'TS PETIT BOIS': 'closed',
  'TK MANESSIER': 'closed',
  'TK CLARINES': 'closed',
  'TK LIEVRE BLANC 1': 'closed',
  'TK LIEVRE BLANC 2': 'closed',
  'TK POLETTA': 'closed',
  'TK SEVOLIERE': 'closed',
  'TK DAHU': 'closed',
  'LES LUTINS': 'closed',
  'TSD FORT': 'closed',
  'TS CHARDONNET': 'closed',
  'TK BELLECOMBE': 'closed',
  'TK BELLECOMBE 1': 'closed',
  'TK BELLECOMBE 2': 'closed',
  'TSD MONT-VALAISAN': 'closed',
  'TSD MOULINS': 'closed',
  'TL LES SUCHES': 'open',
  'SG BOSCO EXPRESS': 'open',
  'SG MAISON BLANCHE': 'closed',
  'NA EDELWEISS': 'closed',
  'NA BABY NASTRO 1': 'closed',
  'NA BABY NASTRO 2': 'closed',
  'SG CHALET EXPRESS': 'open',
  'SG LA COMBE': 'open',
  'SG CHAZ DURA EXP*': 'open',
  'SG * INTERMEDIA': 'closed',
  'SG CHAZ DURA': 'closed',
  'SC PILONI': 'open',
  'SC GRAN TESTA': 'open',
  'NA NASTRO GALLERY': 'closed',
  'SG BELVEDERE': 'closed',
  'SG FOURCLAZ EXP': 'closed',
  'SG P.S BERNARDO EX': 'closed',
  'SG ARGILLIEN EXP.': 'closed',
  'SG ARNOUVAZ': 'closed'
});
