import lifts from '../lifts/index.js';

lifts('lesarcs', 'html', {
  '2300': 'open',
  Vallandry: 'open',
  Derby: 'open',
  Grizzly: 'open',
  Peisey: 'open',
  Parchey: 'open',
  '1Er Virages': 'open',
  Cabri: 'open',
  '1Ere Glisse': 'open',
  Lonzagne: 'open',
  Funiculaire: 'open',
  Arpette: 'closed',
  Cachette: 'open',
  'Mont Blanc.': 'closed',
  Clocheret: 'closed',
  Combettes: 'open',
  Millerette: 'open',
  Snowpark: 'closed',
  Tommelet: 'open',
  Vezaille: 'open',
  Dahu: 'open',
  'Transarc 1': 'open',
  'Transarc 2': 'closed',
  Villards: 'open',
  Carreley: 'closed',
  Vagere: 'open',
  Charmettoger: 'open',
  'Jardin Alpin': 'open',
  '1Ere Glisse 1800': 'open',
  '1Ers Virages 1800': 'open',
  'Aiguille Rouge..': 'closed',
  Varet: 'closed',
  Arcabulle: 'closed',
  'Pre St Esprit': 'closed',
  "Bois De L'ours.": 'closed',
  Comborciere: 'closed',
  Marmottes: 'closed',
  Plagnettes: 'closed',
  'Grand Col.': 'closed',
  Lanchettes: 'closed',
  'St Jacques.': 'closed',
  'Lac Des Combes': 'open',
  Rhodos: 'open',
  Eldorador: 'open',
  Eterlou: 'open',
  'Flamme Olympique': 'open',
  'Plan Vert.': 'closed',
  Cabriolet: 'closed',
  Villaroger: 'closed',
  Droset: 'closed',
  Rhonaz: 'open',
  Azure: 'closed'
});
