const lifts = require('../lifts');

lifts('lesarcs', 'html', {
  '2300': 'open',
  'ARC EN CIEL': 'open',
  'ARPETTE.': 'closed',
  'CACHETTE.': 'open',
  'MONT BLANC.': 'closed',
  'CLOCHERET.': 'closed',
  'COMBETTES.': 'open',
  'MILLERETTE': 'closed',
  'SNOWPARK': 'closed',
  'TOMMELET': 'closed',
  'VEZAILLE': 'open',
  'DAHU': 'open',
  'TRANSARC 1': 'scheduled',
  'TRANSARC 2': 'closed',
  'VILLARDS': 'open',
  'CARRELEY.': 'closed',
  'VAGERE.': 'open',
  'CHARMETTOGER.': 'open',
  'JARDIN ALPIN': 'open',
  '1ers VIRAGES 1800': 'open',
  '1ere GLISSE 1800': 'open',
  'AIGUILLE ROUGE..': 'closed',
  'VARET': 'closed',
  'CABRIOLET': 'open',
  'ARCABULLE': 'closed',
  'PRE ST ESPRIT': 'open',
  "BOIS DE L'OURS": 'closed',
  'COMBORCIERE': 'closed',
  'MARMOTTES.': 'open',
  'PLAGNETTES.': 'closed',
  'GRAND COL.': 'closed',
  'LANCHETTES': 'closed',
  'ST JACQUES.': 'closed',
  'LAC DES COMBES': 'open',
  'RHODOS': 'open',
  'PLAN VERT.': 'closed',
  'ELDORADOR.': 'open',
  'ETERLOU': 'open',
  'FLAMME OLYMPIQUE': 'closed',
  'DROSET.': 'closed',
  'PLAN DES VIOLETTES': 'scheduled',
  'REPLAT.': 'open',
  'RHONAZ.': 'open',
  'TETRAS': 'open',
  'VALLANDRY': 'open',
  'LONZAGNE': 'open',
  'DERBY': 'closed',
  'GRIZZLY': 'closed',
  'PEISEY': 'open',
  'PARCHEY': 'scheduled',
  '1ER VIRAGES': 'scheduled',
  'CABRI.': 'scheduled',
  '1ERE GLISSE': 'scheduled'
});
