const lifts = require('../lifts');

lifts('lesarcs', 'html', {
  'ARC EN CIEL': 'scheduled',
'ARPETTE.': 'scheduled',
'CACHETTE.': 'scheduled',
'MONT BLANC.': 'scheduled',
'CLOCHERET.': 'scheduled',
'COMBETTES.': 'scheduled',
'MILLERETTE': 'closed',
'SNOWPARK': 'scheduled',
'TOMMELET': 'scheduled',
'VEZAILLE': 'scheduled',
'AIGUILLE ROUGE..': 'closed',
'VARET': 'scheduled',
'CABRIOLET': 'open',
'ARCABULLE': 'scheduled',
'PRE ST ESPRIT': 'scheduled',
'BOIS DE L\'OURS': 'scheduled',
'COMBORCIERE': 'scheduled',
'MARMOTTES.': 'scheduled',
'PLAGNETTES.': 'scheduled',
'GRAND COL.': 'scheduled',
'LANCHETTES': 'scheduled',
'ST JACQUES.': 'scheduled',
'LAC COMBES 1': 'scheduled',
'RHODOS': 'scheduled',
'PLAN VERT.': 'scheduled',
'ELDORADOR.': 'scheduled',
'ETERLOU': 'scheduled',
'FLAMME OLYMPIQUE': 'scheduled',
'LONZAGNE': 'scheduled',
'DERBY': 'scheduled',
'GRIZZLY': 'scheduled',
'PEISEY': 'scheduled',
'VALLANDRY': 'scheduled',
'2300': 'scheduled',
'PARCHEY': 'scheduled',
'CABRI.': 'scheduled',
'COMBE.': 'closed',
'FLOCON.': 'scheduled',
'LIAISON ARCS PLAGN': 'scheduled',
'DAHU': 'open',
'TRANSARC 1': 'scheduled',
'TRANSARC 2': 'scheduled',
'VILLARDS': 'scheduled',
'CARRELEY.': 'scheduled',
'VAGERE.': 'scheduled',
'CHARMETTOGER.': 'scheduled',
'JARDIN ALPIN': 'scheduled',
'MUR ESCALADE': 'scheduled',
'ARC 1800 - ARC 2000': 'scheduled',
'DROSET.': 'scheduled',
'PLAN DES VIOLETTES': 'scheduled',
'REPLAT.': 'scheduled',
'RHONAZ.': 'closed',
'TETRAS': 'scheduled'
});
