import lifts from '../lifts/index.js';

lifts('lesmenuires', 'html', {
  Preyerand: 'open',
  'Roc 1': 'open',
  'Roc 2': 'closed',
  Becca: 'open',
  Bettex: 'open',
  Menuires: 'open',
  'Jardin Enfants': 'open',
  Stade: 'open',
  Pelvoux: 'open',
  'Bruyeres 1': 'open',
  'Bruyeres 2': 'closed',
  'Mont De La Chambre': 'closed',
  Doron: 'open',
  'Sunny Express': 'open',
  Bruyeres: 'open',
  Plans: 'open',
  Reberty: 'open',
  'Pointe De La Masse': 'open',
  Tortollet: 'open',
  Masse: 'closed',
  Croisette: 'open',
  'Saint Martin 1': 'open',
  Granges: 'closed',
  'Saint Martin Express': 'open',
  Teppes: 'closed',
  Village: 'open',
  'Biolley 1': 'open',
  'Biolley 2': 'open'
});
