const lifts = require('../lifts');

lifts('lesmenuires', 'html', {
  'Masse 1': 'scheduled',
  'Pointe De La Masse': 'scheduled',
  Croisette: 'scheduled',
  Reberty: 'scheduled',
  Tortollet: 'scheduled',
  Masse: 'scheduled',
  'Bruyères 1': 'scheduled',
  'Bruyères 2': 'scheduled',
  'Mont Chambre.': 'scheduled',
  Doron: 'scheduled',
  'Sunny Express': 'scheduled',
  'Bruy Res': 'scheduled',
  Plans: 'scheduled',
  'St Martin 1': 'scheduled',
  Granges: 'scheduled',
  'St Martin Express': 'scheduled',
  Teppes: 'scheduled',
  Village: 'scheduled',
  'Biolley 1': 'scheduled',
  'Biolley 2': 'scheduled',
  Preyerand: 'scheduled',
  'Roc 1': 'scheduled',
  'Roc 2': 'scheduled',
  Becca: 'scheduled',
  Bettex: 'scheduled',
  Menuires: 'scheduled',
  'Jardin Enfants': 'scheduled',
  Stade: 'scheduled',
  Pelvoux: 'scheduled',
});
