const lifts = require('../lifts');

lifts('megeve', 'html', {
'CAISSE CENTRALE': 'scheduled',
'CAISSE DANDRY': 'scheduled',
'CAISSE JAILLET': 'scheduled',
'CAISSE LA CRY': 'scheduled',
'CAISSE LA GIETTAZ': 'scheduled',
'CAISSE OFFICE DE TOURISME COMBLOUX': 'open',
'CAISSE OFFICE DE TOURISME CORDON': 'open',
'LIAISON CALECHE': 'scheduled',
'LIAISON SKI COTE 2000 > ROCHEBRUNE': 'closed',
'LIAISON SKI JAILLET > COMBLOUX': 'scheduled',
'LIAISON SKI JAILLET > GIETTAZ': 'scheduled',
'LIAISON SKI ROCHEBRUNE > COTE 2000': 'closed',
'TC BETTEX': 'open',
'TC CABOCHE': 'scheduled',
'TC CHAMOIS': 'scheduled',
'TC JAILLET': 'scheduled',
'TC MONT D ARBOIS': 'scheduled',
'TC PRINCESSE': 'scheduled',
'TK 7 NAINS': 'scheduled',
'TK BETTEX': 'open',
'TK BONJOURNAL': 'scheduled',
'TK BOSSES': 'open',
'TK BOUCHET': 'scheduled',
'TK BRONS': 'scheduled',
'TK CABOCHON': 'scheduled',
'TK CHARMOTS': 'scheduled',
'TK COL': 'open',
'TK COMMUNAILLES': 'open',
'TK COVAGNET': 'scheduled',
'TK CREVE COEUR': 'scheduled',
'TK DANDRY': 'scheduled',
'TK DARBELIN': 'scheduled',
'TK DEBUTANT': 'open',
'TK DEBUTANTS': 'scheduled',
'TK ECOLE': 'open',
'TK ETUDIANTS': 'scheduled',
'TK EVASION': 'open',
'TK FIEUX': 'closed',
'TK FREBOUGE': 'scheduled',
'TK FREDDY': 'open',
'TK GARETTES': 'scheduled',
'TK GOUET': 'open',
'TK GRAND VORASSET': 'scheduled',
'TK HERNEY 1': 'scheduled',
'TK HERNEY 2': 'scheduled',
'TK LANCHETTES': 'scheduled',
'TK LUTINS': 'scheduled',
'TK MANDARINES': 'scheduled',
'TK MOUTELY': 'closed',
'TK MOWGLI': 'scheduled',
'TK PATTES 1': 'scheduled',
'TK PATTES 2': 'scheduled',
'TK PETIT BOIS': 'closed',
'TK PETIT VORASSET': 'scheduled',
'TK PLAINE JOUX': 'scheduled',
'TK PLATEAU': 'open',
'TK ROCHEFORT': 'scheduled',
'TK TORRAZ': 'scheduled',
'TK TOUR': 'scheduled',
'TK VANAY': 'scheduled',
'TK VENAZ': 'open',
'TK VILLAGE': 'scheduled',
'TP JARDINEIGE': 'scheduled',
'TP LADY': 'scheduled',
'TP OURSON': 'scheduled',
'TP PIOU PIOU': 'scheduled',
'TP PLAN': 'scheduled',
'TP SCHUSS': 'scheduled',
'TPH ROCHARBOIS': 'scheduled',
'TPH ROCHEBRUNE': 'scheduled',
'TPH ST GERVAIS': 'open',
'TS ARBOIS': 'open',
'TS CHATTRIX': 'open',
'TS CHEF LIEU': 'open',
'TS EPAULE': 'closed',
'TS MONT JOLY': 'closed',
'TS MONT JOUX III': 'open',
'TS PIERRE PLATE': 'open',
'TSD ALPETTE': 'scheduled',
'TSD BEAUREGARD': 'scheduled',
'TSD CHRIST': 'open',
'TSD CHRISTOMET': 'scheduled',
'TSD CROIX': 'open',
'TSD IDEAL': 'scheduled',
'TSD MONT JOUX': 'scheduled',
'TSD MONT ROSSET': 'open',
'TSD PERTUIS': 'scheduled',
'TSD PETITE FONTAINE': 'scheduled',
'TSF COTE 2000': 'closed',
'TSF GRANDE RARE': 'scheduled',
'TSF GRANDS CHAMPS': 'scheduled',
'TSF JARDIN': 'scheduled',
'TSF JOUTY': 'scheduled',
'TSF PETIT ROCHEBRUNE': 'scheduled',
'TSF PRELLET': 'closed',
'TSF PRES': 'scheduled',
'TSF RADAZ': 'closed',
'TSF RAVINE': 'scheduled',
'TSF TETE TORRAZ': 'scheduled',
'lesportesdumontblanc.fr': 'open'

});
