const lifts = require('../lifts');

lifts('megeve', 'html', {
  'TSD BEAUREGARD': 'scheduled',
  'TSD PERTUIS': 'scheduled',
  'TSF JOUTY': 'scheduled',
  'TK BRONS': 'scheduled',
  'TK CREVE COEUR': 'scheduled',
  'TK GARETTES': 'scheduled',
  'TK LA CRY': 'scheduled',
  'TK MOWGLI': 'scheduled',
  'TK DANDRY': 'scheduled',
  'TK DARBELIN': 'scheduled',
  'TK FIEUX': 'closed',
  'TK FREBOUGE': 'scheduled',
  'TK HERNEY 1': 'scheduled',
  'TK HERNEY 2': 'scheduled',
  'TK LUTINS': 'scheduled',
  'TPH ROCHARBOIS': 'scheduled',
  'TPH ROCHEBRUNE': 'scheduled',
  'TC CABOCHE': 'scheduled',
  'TC CHAMOIS': 'scheduled',
  'TSD ALPETTE': 'scheduled',
  'TSD PETITE FONTAINE': 'scheduled',
  'TSF COTE 2000': 'scheduled',
  'TSF GRANDS CHAMPS': 'scheduled',
  'TSF JARDIN': 'scheduled',
  'TSF PETIT ROCHEBRUNE': 'scheduled',
  'TSF RADAZ': 'scheduled',
  'TK CABOCHON': 'scheduled',
  'TK LANCHETTES': 'scheduled',
  'TK MOUTELY': 'closed',
  'TK ROCHEFORT': 'scheduled',
  'TK TOUR': 'scheduled',
  'TK VILLAGE': 'closed',
  'TP LADY': 'scheduled',
  'TP SCHUSS': 'scheduled',
  'TC MONT D ARBOIS': 'scheduled',
  'TC PRINCESSE': 'scheduled',
  'TSD IDEAL': 'scheduled',
  'TK DEBUTANTS': 'scheduled',
  'TK ETUDIANTS': 'scheduled',
  'TK GRAND VORASSET': 'closed',
  'TK MANDARINES': 'scheduled',
  'TK PETIT BOIS': 'closed',
  'TK PETIT VORASSET': 'scheduled',
  'TP JARDINEIGE': 'scheduled',
  'TP OURSON': 'scheduled',
  'TC JAILLET': 'scheduled',
  'TSD CHRISTOMET': 'scheduled',
  'TSF PRES': 'scheduled',
  'TSF RAVINE': 'scheduled',
  'TK PATTES 1': 'scheduled',
  'TP PIOU PIOU': 'scheduled',
  'TSF GRANDE RARE': 'scheduled',
  'TSF TETE TORRAZ': 'scheduled',
  'TK BONJOURNAL': 'scheduled',
  'TK CHARMOTS': 'scheduled',
  'TK COVAGNET': 'scheduled',
  'TK TORRAZ': 'closed',
  'TP PLAN': 'scheduled',
  'TPH ST GERVAIS': 'open',
  'TC BETTEX': 'open',
  'TSD CROIX': 'open',
  'TSD MONT JOUX': 'open',
  'TSD MONT ROSSET': 'open',
  'TS ARBOIS': 'open',
  'TS MONT JOUX III': 'closed',
  'TS PIERRE PLATE': 'open',
  'TK BETTEX': 'open',
  'TK BOSSES': 'open',
  'TK COL': 'open',
  'TK COMMUNAILLES': 'open',
  'TK ECOLE': 'open',
  'TK EVASION': 'open',
  'TK FREDDY': 'open',
  'TK VENAZ': 'open',
  'TP MARMOTTONS': 'open',
  'TSD CHATTRIX': 'open',
  'TSD CHRIST': 'open',
  'TSD EPAULE': 'open',
  'TS CHEF LIEU': 'open',
  'TS MONT JOLY': 'open',
  'TK DEBUTANT': 'open',
  'TK GOUET': 'open',
  'TK PLATEAU': 'open',
  'TK VANAY': 'open'
});
