const lifts = require('../lifts');

lifts('megeve', 'html', {
  'Tsd Beauregard': 'scheduled',
  'Tsd Pertuis': 'scheduled',
  'Tsf Jouty': 'scheduled',
  'Tk Brons': 'scheduled',
  'Tk Creve Coeur': 'scheduled',
  'Tk Garettes': 'scheduled',
  'Tk La Cry': 'scheduled',
  'Tk Mowgli': 'scheduled',
  'Tk Dandry': 'scheduled',
  'Tk Darbelin': 'scheduled',
  'Tk Fieux': 'closed',
  'Tk Frebouge': 'scheduled',
  'Tk Herney 1': 'scheduled',
  'Tk Herney 2': 'scheduled',
  'Tk Lutins': 'scheduled',
  'Tph Rocharbois': 'scheduled',
  'Tph Rochebrune': 'scheduled',
  'Tc Caboche': 'scheduled',
  'Tc Chamois': 'scheduled',
  'Tsd Alpette': 'scheduled',
  'Tsd Petite Fontaine': 'scheduled',
  'Tsf Cote 2000': 'scheduled',
  'Tsf Grands Champs': 'scheduled',
  'Tsf Jardin': 'scheduled',
  'Tsf Petit Rochebrune': 'scheduled',
  'Tsf Radaz': 'scheduled',
  'Tk Cabochon': 'scheduled',
  'Tk Lanchettes': 'scheduled',
  'Tk Moutely': 'closed',
  'Tk Rochefort': 'scheduled',
  'Tk Tour': 'scheduled',
  'Tk Village': 'closed',
  'Tp Lady': 'scheduled',
  'Tp Schuss': 'scheduled',
  'Tc Mont D Arbois': 'scheduled',
  'Tc Princesse': 'scheduled',
  'Tsd Ideal': 'scheduled',
  'Tk Debutants': 'scheduled',
  'Tk Etudiants': 'scheduled',
  'Tk Grand Vorasset': 'closed',
  'Tk Mandarines': 'scheduled',
  'Tk Petit Bois': 'closed',
  'Tk Petit Vorasset': 'scheduled',
  'Tp Jardineige': 'scheduled',
  'Tp Ourson': 'scheduled',
  'Tc Jaillet': 'scheduled',
  'Tsd Christomet': 'scheduled',
  'Tsf Pres': 'scheduled',
  'Tsf Ravine': 'scheduled',
  'Tk Pattes 1': 'scheduled',
  'Tp Piou Piou': 'scheduled',
  'Tsf Grande Rare': 'scheduled',
  'Tsf Tete Torraz': 'scheduled',
  'Tk Bonjournal': 'scheduled',
  'Tk Charmots': 'scheduled',
  'Tk Covagnet': 'scheduled',
  'Tk Torraz': 'closed',
  'Tp Plan': 'scheduled',
  'Tph St Gervais': 'open',
  'Tc Bettex': 'open',
  'Tsd Croix': 'open',
  'Tsd Mont Joux': 'open',
  'Tsd Mont Rosset': 'open',
  'Ts Arbois': 'open',
  'Ts Mont Joux Iii': 'closed',
  'Ts Pierre Plate': 'open',
  'Tk Bettex': 'open',
  'Tk Bosses': 'open',
  'Tk Col': 'open',
  'Tk Communailles': 'open',
  'Tk Ecole': 'open',
  'Tk Evasion': 'open',
  'Tk Freddy': 'open',
  'Tk Venaz': 'open',
  'Tp Marmottons': 'open',
  'Tsd Chattrix': 'open',
  'Tsd Christ': 'open',
  'Tsd Epaule': 'open',
  'Ts Chef Lieu': 'open',
  'Ts Mont Joly': 'open',
  'Tk Debutant': 'open',
  'Tk Gouet': 'open',
  'Tk Plateau': 'open',
  'Tk Vanay': 'open',
});
