import lifts from '../lifts/index.js';

lifts('meribel', 'html', {
  'Cote Brune': 'scheduled',
  Chalets: 'open',
  'Combes 1': 'scheduled',
  'Combes 2': 'scheduled',
  'Roc De Tougne': 'scheduled',
  Arolles: 'scheduled',
  Doron: 'scheduled',
  Ourson: 'scheduled',
  'Table Verte': 'scheduled',
  'Mont Vallon': 'scheduled',
  'Mûres Rouges.': 'scheduled',
  'Pas Du Lac 1': 'scheduled',
  'Pas Du Lac 2': 'scheduled',
  Aigle: 'scheduled',
  'Plattières': 'scheduled',
  Bouquetin: 'scheduled',
  Chatelet: 'scheduled',
  'Plan Des Mains': 'scheduled',
  'Rhodos 1': 'scheduled',
  'Rhodos 2': 'scheduled',
  'Saulire Express 1': 'scheduled',
  'Saulire Express 2': 'closed',
  Adret: 'scheduled',
  Altiport: 'scheduled',
  'Dent Burgin': 'scheduled',
  Golf: 'scheduled',
  Loze: 'scheduled',
  Morel: 'scheduled',
  'Côtes': 'scheduled',
  Inuits: 'scheduled',
  Loupiot: 'scheduled',
  Fontany: 'scheduled',
  'Tougnète 1': 'scheduled',
  Legends: 'scheduled',
  'Tougnète 2': 'scheduled',
  Cherferie: 'scheduled',
  Olympic: 'closed',
  Arpasson: 'scheduled',
  Caves: 'scheduled',
  Stade: 'scheduled',
  'Olympe 1': 'scheduled',
  'Olympe 2': 'scheduled',
  'Olympe 3': 'scheduled'
});
