const lifts = require('../lifts');

lifts('meribel', 'html', {
  'Rhodos 1': 'scheduled',
  'Rhodos 2': 'scheduled',
  'Saulire Express 1': 'scheduled',
  'Saulire Express 2': 'scheduled',
  Adret: 'scheduled',
  Altiport: 'scheduled',
  'Dent Burgin': 'scheduled',
  Golf: 'scheduled',
  'Loze Express': 'scheduled',
  Morel: 'scheduled',
  Côtes: 'scheduled',
  Fontany: 'scheduled',
  Loupiot: 'scheduled',
  'Tougnète 1': 'scheduled',
  Legends: 'scheduled',
  'Tougnète 2': 'scheduled',
  Cherferie: 'scheduled',
  Olympic: 'scheduled',
  Arpasson: 'scheduled',
  Caves: 'scheduled',
  Stade: 'scheduled',
  'Olympe 1': 'scheduled',
  'Olympe 2': 'scheduled',
  'Olympe 3': 'scheduled',
  'Cote Brune': 'scheduled',
  Chalets: 'open',
  Combes: 'scheduled',
  'Roc De Tougne': 'scheduled',
  Arolles: 'scheduled',
  Doron: 'scheduled',
  Ourson: 'scheduled',
  'Table Verte': 'scheduled',
  'Mont Vallon': 'closed',
  'Mûres Rouges': 'scheduled',
  'Pas Du Lac 1': 'scheduled',
  'Pas Du Lac 2': 'scheduled',
  Aigle: 'scheduled',
  Plattières: 'scheduled',
  Bouquetin: 'scheduled',
  Chatelet: 'scheduled',
  'Plan Des Mains': 'scheduled',
});
