const lifts = require('../lifts');

lifts('mtbrighton', 'html', {
  'Bunny': 'closed',
  'Snowshoe': 'closed',
  'Thalacker’s': 'closed',
  'Sidewinder': 'closed',
  'Sawtooth Ridge': 'closed',
  'Easy Street': 'closed',
  'Gasoline Alley': 'closed',
  'Ryan’s Run': 'closed',
  'Flatiron': 'closed',
  'Larkspur': 'closed',
  'Crosscut': 'closed',
  'Blue Sky': 'closed',
  'Hare': 'closed',
  'Chicken Chute': 'closed',
  'Cheetah': 'closed',
  'Big Riskey': 'closed',
  'Grand River': 'closed',
  'Osprey': 'closed',
  'Golden Eagle': 'closed',
  'Perk’s Folly': 'closed',
  'Challenge': 'closed',
  'Sunrise Bowl': 'closed',
  'Ledges': 'closed',
  'Gopher': 'closed',
  'Riglet Park': 'closed',
});
