const lifts = require('../lifts');

lifts('niseko', 'html', {
  'Annupuri Gondola': 'closed',
  'Dream Quad Lift #1': 'closed',
  'Jumbo Quad Lift #1': 'closed',
  'Jumbo Pair Lift #2': 'closed',
  'Jumbo Pair Lift #3': 'closed',
  'Jumbo Pair Lift #4': 'closed',
  'Niseko Gondola': 'closed',
  'Upper Village Gondola': 'closed',
  'Village Express': 'closed',
  'Community Chair': 'closed',
  'Bonzai Chair': 'closed',
  'Mori No Chair': 'closed',
  'Country Road Chair': 'closed',
  'Wonderland Chair': 'closed',
  'Ace Family Quad Lift': 'closed',
  'Ace Pair Lift #1': 'closed',
  'Ace Quad Lift #2 (Center 4)': 'closed',
  'Ace Pair Lift #3': 'closed',
  'Ace Pair Lift #4': 'closed',
  'Hirafu Gondola': 'closed',
  'Holiday Pair Lift #1': 'closed',
  'King Pair Lift #1': 'closed',
  'King Quad Lift #2': 'closed',
  'King Hooded Quad Lift #3': 'closed',
  'King Lift #4': 'closed',
  'Swinging Monkey': 'closed',
  'Hanazono Hooded Quad #1': 'closed',
  'Hanazono Quad Lift #2': 'closed',
  'Hanazono Hooded Quad Lift #3': 'closed'
});
