const lifts = require('../lifts');

lifts('palisades', 'json', {
  'Aerial Tram': 'open',
  'Exhibition': 'closed',
  'Far East Express': 'closed',
  'First Venture': 'closed',
  'Funitel': 'closed',
  'Kaya': 'closed',
  'KT-22 Express': 'closed',
  'Olympic Lady': 'closed',
  'Red Dog': 'closed',
  'Resort Chair': 'closed',
  'SnoVentures Carpet': 'closed',
  'Wa She Shu': 'closed',
  'Bailey\'s Beach': 'closed',
  'Belmont': 'closed',
  'Big Blue Express': 'closed',
  'Broken Arrow': 'closed',
  'Emigrant': 'closed',
  'Gold Coast Express': 'closed',
  'Granite Chief': 'closed',
  'Headwall Express': 'closed',
  'Mountain Meadow': 'closed',
  'Shirley Lake Express': 'closed',
  'Siberia Express': 'closed',
  'Silverado': 'closed',
  'Solitude': 'closed',
  'The Pulley': 'closed',
  'Boomer': 'closed',
  'Shaka': 'closed',
  'Wylee': 'closed',
});
