const lifts = require('../lifts');

lifts('parkcity', 'html', {
  '3 Kings Lift': 'hold',
  '9990 Express': 'closed',
  'Bonanza Lift': 'hold',
  'Cabriolet': 'closed',
  'Crescent Lift': 'hold',
  'Day Break': 'closed',
  'Dreamcatcher': 'closed',
  'Dreamscape': 'closed',
  'Eagle Lift': 'closed',
  'First Time Lift': 'hold',
  'Flat Iron': 'closed',
  'Frostwood Gondola': 'closed',
  'High Meadow': 'closed',
  'Iron Mtn. Express': 'closed',
  'Jupiter Lift': 'hold',
  'King Con Lift': 'closed',
  'McConkey\'s Lift': 'hold',
  'Mine Cart': 'closed',
  'Motherlode Lift': 'closed',
  'Mule Train': 'closed',
  'Orange Bubble Express': 'closed',
  'Over and Out': 'closed',
  'PayDay Lift': 'closed',
  'Peak 5': 'closed',
  'Pioneer Lift': 'closed',
  'Quicksilver Canyons Side': 'closed',
  'Quicksilver PC Side': 'closed',
  'Red Pine Gondola': 'closed',
  'Rip Cord': 'closed',
  'Saddleback Express': 'closed',
  'Shortcut': 'closed',
  'Silver Lining': 'closed',
  'Silver Star Lift': 'closed',
  'Silverlode Lift': 'hold',
  'Sun Peak Express': 'closed',
  'Sunrise': 'closed',
  'Super Condor Express': 'closed',
  'Sweet Pea': 'closed',
  'Thaynes Lift': 'hold',
  'Timberline': 'closed',
  'Tombstone Express': 'closed',
  'Town Lift': 'closed'
});
