const lifts = require('../lifts');

lifts('pontedilegno-tonale', 'html', {
  'Casola': 'closed',
  'Valbione': 'closed',
  'Corno d\'Aola': 'closed',
  'Angelo': 'closed',
  'Campo Scuola Cida': 'closed',
  'Sozzine': 'closed',
  'Ponte di Legno - Colonia Vigili': 'closed',
  'Roccolo Ventura': 'closed',
  'La Croce': 'closed',
  'Santa Giulia': 'closed',
  'Doss delle Pertiche': 'closed',
  'Colonia Vigili - Tonale': 'closed',
  'Nigritella': 'closed',
  'Bleis': 'closed',
  'Tre Larici': 'closed',
  'Serodine': 'closed',
  'Cadì Sit': 'closed',
  'Scoiattolo': 'closed',
  'Presanella': 'closed',
  'Vittoria': 'closed',
  'Tubbo': 'closed',
  'Alpe Alta': 'closed',
  'Valena': 'closed',
  'Valbiolo': 'closed',
  'Tonale Occidentale': 'closed',
  'Contrabbandieri': 'closed',
  'Paradiso': 'closed',
  'Presena': 'closed'
});
