const lifts = require('../lifts');

lifts('roccaraso', 'html', {
  'Valle delle Gravare': 'closed',
  'Gravare di Sotto': 'closed',
  Macchione: 'closed',
  Aremogna: 'closed',
  Pallottieri: 'open',
  'Campo Scuola': 'closed',
  'ValleVerde 1': 'closed',
  'ValleVerde 2': 'closed',
  'Aremogna Crete Rosse': 'closed',
  'Crete Rosse 1': 'closed',
  'Pino Solitario': 'closed',
  'Del Pratelletto': 'closed',
  'Monte Pratello': 'closed',
  Valloncello: 'closed',
  Prato: 'closed',
  Vallone: 'closed',
  'Pratello Crete Rosse': 'closed',
  'Lago d’Avoli Orso': 'closed',
  Pizzalto: 'closed',
  'Paradiso 1 e 2': 'closed',
  'Gravare-ToppeTes': 'closed',
  'Pizzalto-Gravare': 'closed',
});
