import lifts from '../lifts/index.js';

lifts('skiwelt', 'json', {
  '6er Gondelbahn Hochbrixen': 'open',
  'Kälbersalvenbahn': 'open',
  Zinsbergbahn: 'open',
  Poldangerlift: 'open',
  Jochbahn: 'open',
  Filzbodenbahn: 'open',
  'Würstlexpress': 'open',
  'Übungslift Hochbrixen': 'open',
  'Skischullift Hochbrixen': 'open',
  '8er- SkiWeltbahn': 'open',
  Sonnenlift: 'open',
  'Schusterbühellift': 'open',
  Sonnenband: 'open',
  '10er Gondelbahn Hartkaiserbahn': 'open',
  Marcher: 'open',
  'Vetterstätt Zauberteppich': 'open',
  'Vetterstätt': 'open',
  Kirchbichl: 'open',
  Schmiedalm: 'open',
  "Ellmi's Zauberteppich I": 'open',
  'Ellmi&#39;s Zauberteppich II': 'open',
  Hausberg: 'open',
  "Ellmi's 6er": 'open',
  Kaiserexpress: 'open',
  'Köglbahn': 'open',
  Almbahn: 'open',
  Tanzbodenbahn: 'open',
  Astbergbahn: 'open',
  Maxilift: 'open',
  'Zauberteppich Astberg': 'open',
  'Ellmi´s Zauberteppich III': 'open',
  '8er Gondelbahn Salvenbahn I': 'open',
  '8er Gondelbahn Salvenbahn II': 'open',
  '10er Gondelbahn Salvistabahn': 'open',
  'Hohe Salve I': 'open',
  Rigibahn: 'open',
  Schernthannbahn: 'open',
  Foischingbahn: 'open',
  'Zauberteppich Bodenschmied': 'open',
  'Zauberteppich Högerfeld': 'open',
  Kasbichlbahn: 'open',
  'Tellerschlepplift Salvista': 'open',
  Pfaringlift: 'closed',
  '4EUB Brandstadl': 'closed',
  '8er Gondelbahn Brandstadl I': 'open',
  '8er Gondelbahn Brandstadl II': 'open',
  Osthang: 'open',
  Ostlift: 'open',
  'Südhang': 'open',
  Eiberg: 'open',
  'Kummereralm-Lift': 'open',
  Muldenbahn: 'open',
  Aualm: 'open',
  'Hochfeldlift-Schwoich': 'open',
  'Babylift Schwoich': 'open',
  Babylift: 'open',
  'Übungslift - Berg': 'open',
  'Übungslift - Dorf': 'open',
  '10er Gondelbahn Hexenwasser': 'open',
  '8er Gondelbahn Hohe Salve': 'open',
  '4er Sesselbahn Keat': 'open',
  'Stöckl': 'open',
  Hexen6er: 'open',
  Rinner: 'open',
  'Hans im Glück': 'open',
  'Siller-Keat': 'open',
  Knolln: 'open',
  'Hexenteppich 1': 'open',
  'Hexenteppich 2': 'open',
  'Mühlbichl (Übungsbereich im Dorf)': 'open',
  '6er Gondelbahn Alpenrosenbahn I': 'open',
  '6er Gondelbahn Alpenrosenbahn II': 'open',
  '8er Gondelbahn Choralmbahn': 'open',
  '8er Gondelbahn KiWest': 'open',
  Talkaser: 'open',
  Laubkogel: 'open',
  Fleiding: 'open',
  Windauberg: 'open',
  Gampenkogel: 'open',
  Sammer: 'open',
  Schneeberg: 'open',
  'Förderband Kelchsau': 'closed'
});
