const lifts = require('../lifts');

lifts('skiwelt', 'html', {
  '6er Gondelbahn Hochbrixen': 'open',
  'Kälbersalvenbahn': 'closed',
  Zinsbergbahn: 'open',
  Poldangerlift: 'closed',
  Jochbahn: 'closed',
  Filzbodenbahn: 'closed',
  'Würstlexpress': 'closed',
  'Übungslift Hochbrixen': 'closed',
  'Skischullift Hochbrixen': 'closed',
  '8er- SkiWeltbahn': 'closed',
  Sonnenlift: 'closed',
  'Schusterbühellift': 'closed',
  Sonnenband: 'closed',
  '10er Gondelbahn Hartkaiserbahn': 'open',
  Marcher: 'closed',
  'Vetterstätt Zauberteppich': 'closed',
  'Vetterstätt': 'closed',
  Kirchbichl: 'closed',
  Schmiedalm: 'closed',
  'Ellmi\'s Zauberteppich I': 'closed',
  'Ellmi \'s Zauberteppich II': 'closed',
  Hausberg: 'closed',
  'Ellmi\'s 6er': 'closed',
  Kaiserexpress: 'closed',
  'Köglbahn': 'closed',
  Almbahn: 'closed',
  Tanzboden: 'closed',
  '4er Sesselbahn Astberg': 'open',
  Maxilift: 'closed',
  'Zauberteppich Astberg': 'closed',
  '8er Gondelbahn Salvenbahn I': 'open',
  '8er Gondelbahn Salvenbahn II': 'open',
  '10er Gondelbahn Salvistabahn': 'open',
  'Hohe Salve I': 'closed',
  Rigibahn: 'closed',
  Schernthannbahn: 'closed',
  Foischingbahn: 'closed',
  'Zauberteppich Bodenschmied': 'closed',
  'Zauberteppich Högerfeld': 'closed',
  Kasbichlbahn: 'closed',
  'Übungslift Itter': 'closed',
  Pfaringlift: 'closed',
  '4EUB Brandstadl': 'closed',
  '8er Gondelbahn Brandstadl I': 'open',
  '8er Gondelbahn Brandstadl II': 'open',
  Osthang: 'closed',
  Ostlift: 'closed',
  'Südhang': 'closed',
  'Eiberg I': 'closed',
  'Eiberg II': 'closed',
  Kummereralm: 'closed',
  Muldenbahn: 'closed',
  Aualm: 'closed',
  Hochalm: 'closed',
  'Hochfeldlift-Schwoich': 'closed',
  'Übungslift Hochfeld-Schwoich': 'closed',
  Babylift: 'closed',
  'Übungslift - Berg': 'closed',
  'Übungslift - Dorf': 'closed',
  '10er Gondelbahn Hexenwasser': 'open',
  '8er Gondelbahn Hohe Salve': 'open',
  '4er Sesselbahn Keat': 'closed',
  'Stöckl': 'closed',
  Hexen6er: 'closed',
  Rinner: 'closed',
  'Hans im Glück': 'closed',
  'Siller-Keat': 'closed',
  Knolln: 'closed',
  'Übungslift': 'closed',
  Hexenteppich: 'closed',
  '6er Gondelbahn Alpenrosenbahn I': 'open',
  '6er Gondelbahn Alpenrosenbahn II': 'open',
  '8er Gondelbahn Choralmbahn': 'closed',
  '8er Gondelbahn KiWest': 'closed',
  Talkaser: 'closed',
  Laubkogel: 'closed',
  Fleiding: 'closed',
  Windauberg: 'closed',
  Gampenkogel: 'closed',
  Sammer: 'closed',
  Schneeberg: 'closed'
});
