const lifts = require("../lifts");

lifts("smuggs", "html", {
  "Curley's Cutback": "open",
  "Dixie's Knoll": "closed",
  Evaporator: "closed",
  "Garden Path": "open",
  Hibernator: "open",
  "Howie’s Wanderer": "open",
  "Log Jam": "open",
  "Lower Morse Liftline": "open",
  "Magic Learning Trail": "open",
  Midway: "open",
  Meadowlark: "open",
  "Sam's Run": "open",
  "Sir Henry's Learning Hill": "open",
  "Snow Snake": "open",
  "Timberrr!": "closed",
  "Upper Morse Liftline": "closed",
  "Burton Riglet Park": "open",
  "Log Jam Terrain Park": "closed",
  "Mogul Mouse's Magic Lift": "open",
  "Morse Highlands Lift": "open",
  "Sir Henry's Glider Lift": "open",
  "Village Lift": "open",
  "Birch Run": "open",
  "Black Bear": "closed",
  "Black Snake": "open",
  Bootlegger: "closed",
  Chute: "open",
  Crossover: "open",
  "Deer Run Glades": "open",
  "Full Nelson": "open",
  "Hangman's": "open",
  "Hangman's Drop": "closed",
  "Harvey's Hideaway": "open",
  "Highlander Glades": "open",
  "Jolly Rodger": "open",
  "Lower Exhibition": "open",
  "Lower Pipeline": "open",
  "Lower Rumrunner": "open",
  "Pipeline Escape": "open",
  "Pirate's Plank": "open",
  "Poacher's Woods": "open",
  "Powder Keg": "open",
  "Practice Slope": "open",
  "Sherwood Forest": "closed",
  "Smugglers' Alley": "open",
  "Snake Bite": "open",
  "Thomke's": "open",
  "Thomke's Express": "open",
  "Treasure Run": "open",
  "Upper Exhibition": "open",
  "Upper Pipeline": "closed",
  "Upper Rumrunner": "open",
  "Birch Run Terrain Park": "open",
  "The Zone Terrain Park": "closed",
  "Sterling Lift": "open",
  "Sterling T-Bar Lift": "open",
  Bermuda: "open",
  "Black Hole": "open",
  Catwalk: "open",
  "Dan's Ford": "open",
  "Doc Dempsey's Glades": "open",
  "Father Bob's": "open",
  Freefall: "closed",
  "Gary B's NW Passage": "open",
  "Goat Path": "open",
  "Knight's Revenge": "open",
  "Lower Catwalk": "open",
  "Lower Chilcoot": "open",
  "Lower Drifter": "open",
  "Lower F.I.S.": "open",
  "Lower Liftline": "open",
  "McPherson's": "open",
  "Moonshiner's Glades": "open",
  "Mulcahy's Link": "open",
  "Norwegian Woods": "open",
  Playground: "open",
  "Red Fox Glades": "open",
  "Robin's Run": "closed",
  "Ruthie's": "open",
  Shakedown: "open",
  "The Shire": "open",
  Shuttle: "open",
  "Three Mountain Glades": "open",
  "Upper Chilcoot": "open",
  "Upper Drifter": "open",
  "Upper F.I.S.": "open",
  "Upper Liftline": "closed",
  Waterfall: "open",
  "Knight's Revenge Gladed Park": "closed",
  "Madonna I Lift": "open",
  "Madonna II Lift": "open",
  "Morse Uphill Access": "open",
  "Sterling Uphill Access": "open",
  "Madonna Uphill Access": "closed",
});
