import lifts from '../lifts/index.js';

lifts('tignes', 'html', {
  'Tc De Toviere': 'closed',
  'Tsd De Fresse': 'closed',
  'Tsd Du Bollin': 'open',
  'Tsd Du Paquis': 'open',
  'Tsd Tommeuses': 'closed',
  'Ts Du Rosset': 'hold',
  'Tsd Des Tufs': 'closed',
  'Tk De Combe Folle': 'closed',
  'Tk Du Lavachet': 'open',
  'Tapis Du Centre': 'open',
  'Tapis Du Claret': 'open',
  'Tc Brevieres': 'open',
  'Tc Des Boisses': 'open',
  'Ts Aiguille Percee': 'closed',
  'Tsd Aiguille Rouge': 'open',
  'Tsd De Chaudannes': 'open',
  'Tsd Du Marais': 'closed',
  'Tsd Palafour': 'open',
  'Ts Des Almes': 'open',
  'Tk Parei': 'open',
  'Tapis 1 Tignes 1800': 'open',
  'Tapis 2 Tignes 1800': 'open',
  'Tsd Des Merles': 'closed',
  'Tsd Du Grattalu': 'closed',
  'Tsd Du Tichot': 'open',
  'Ts Du Col Des Ves': 'scheduled',
  'Ts Du Grand Huit': 'closed',
  'Tk Du Chardonnet': 'open',
  'Tk Du Col Du Palet': 'closed',
  'Tapis Balme 1 & 2': 'open',
  'Fil Neige Replat': 'open',
  Funiculaire: 'scheduled',
  'Tp De Grande Motte': 'scheduled',
  'Tsd De La Vanoise': 'closed',
  'Tsd Des Lanches': 'closed',
  'Téléphérique Grande Motte': 'scheduled',
  'Tc Boisses': 'scheduled',
  'Tc Brévières': 'open',
  'Tc Tovière': 'scheduled',
  'Tsd Bollin': 'open',
  'Tsd Chaudannes': 'scheduled',
  'Tsd Tichot': 'scheduled'
});
