const lifts = require('../lifts');

lifts('vail', 'html', {
  'Avanti Express #2': 'scheduled',
  'Black Forest #27': 'closed',
  'Born Free Express #8': 'closed',
  'Cascade Village #20': 'closed',
  'Eagle Bahn Gondola #19': 'scheduled',
  'Earl\'s Express #38': 'closed',
  'Elvis Bahn #25': 'closed',
  'Game Creek Express #7': 'closed',
  'Golden Peak T-Bar': 'closed',
  'Gondola One': 'scheduled',
  'Gopher Hill #12': 'closed',
  'High Noon Express #5': 'scheduled',
  'Highline Express #10': 'closed',
  'Lightning Coyote #18': 'closed',
  'Lionshead Magic Carpet #34': 'scheduled',
  'Little Eagle #15': 'scheduled',
  'Mongolia Platter #22': 'closed',
  'Mountaintop Express #4': 'scheduled',
  'Northwoods Express #11': 'scheduled',
  'Orient Express #21': 'closed',
  'Patty Bahn': 'closed',
  'Pete\'s Express #39': 'closed',
  'Pride Express #26': 'closed',
  'Rip\'s Ride Carpet #29': 'closed',
  'Riva Bahn Express #6': 'scheduled',
  'Skyline Express #37': 'closed',
  'Sourdough Express #14': 'closed',
  'Sun Down Express #17': 'closed',
  'Sun Up Express #9': 'closed',
  'Tea Cup Express #36': 'closed',
  'Thunder Cat Carpet #35': 'scheduled',
  'Wapiti Platter #24': 'closed',
  'Wildwood Express #3': 'scheduled'
});
