const lifts = require('../lifts');

lifts('val-gardena', 'html', {
  Val: 'closed',
  'Costabella': 'closed',
  'Nives': 'closed',
  'Biancaneve': 'closed',
  'Larciunei': 'closed',
  'Cadepunt': 'closed',
  'Manovia Mickey Mouse': 'closed',
  'Risaccia 1': 'closed',
  'Risaccia 2': 'closed',
  'Dantercepies II': 'closed',
  'Panorama': 'closed',
  'Cir': 'closed',
  'Dantercepies I': 'closed',
  'Val Setus': 'closed',
  'Fungeia': 'closed',
  'Piz Sella': 'closed',
  'Plan de Gralba': 'closed',
  'Comici 1': 'closed',
  'Comici 2': 'closed',
  'Gran Paradiso': 'closed',
  'Sotsaslong': 'closed',
  'Pudra': 'closed',
  'Piz Seteur 1': 'closed',
  'Piz Seteur 2': 'closed',
  'Piz Seteur/Sole': 'closed',
  'Città dei Sassi': 'closed',
  'Forcella Sassolungo': 'closed',
  'Ciampinoi': 'closed',
  'Sasso Levante': 'closed',
  'Ciavazes - Grohmann': 'closed',
  'Piza Pranseies': 'closed',
  'Salei - Rodella': 'closed',
  'Rodella - Des Alpes': 'closed',
  'Norei - Cinque Dita': 'closed',
  'Gabia': 'closed',
  'Saslong': 'closed',
  'Sochers/Ciampinoi': 'closed',
  'Sochers': 'closed',
  'Terza punta': 'closed',
  'Campo Freina': 'closed',
  'S.Cristina-Monte Pana': 'closed',
  'Mont de Seura': 'closed',
  'Sciovia Tschucky': 'closed',
  'Parallel': 'closed',
  'Puntea': 'closed',
  'Cendevaves': 'closed',
  'Col Raiser': 'closed',
  'Tramans': 'closed',
  'Ortisei-Furnes': 'closed',
  'Furnes-Seceda': 'closed',
  'Resciesa': 'closed',
  'Fermeda': 'closed',
  'Catores Martin': 'closed',
  'Cisles': 'closed',
  'Gherdeina Ronda': 'closed',
  'Plan da Tieja': 'closed',
  'Ortisei - Alpe di Siusi': 'closed',
  'Furdenan': 'closed',
  'Palmer': 'closed',
  'Bamby': 'closed',
  'Bullaccia': 'closed',
  'Euro': 'closed',
  'Eurotel 1': 'closed',
  'Floralpina': 'closed',
  'Florian': 'closed',
  'Laurin': 'closed',
  'Leo Demetz': 'closed',
  'Ludylift': 'closed',
  'Marinzen': 'closed',
  'Mezdì': 'closed',
  'Monte Piz - Rif. Icaro': 'closed',
  'Paradiso': 'closed',
  'Punta d\'Oro': 'closed',
  'Sanon': 'closed',
  'Seiser Alm Aerial Cableway': 'closed',
  'Spitzbuehl': 'closed',
  'Steger/Dellai': 'closed',
  'Strega': 'closed',
  'Zur Sonne': 'closed'
});
