const lifts = require('../lifts');

lifts('valdisere', 'html', {
  Funival: 'open',
  'Tph Olympique': 'closed',
  'Tc Daille': 'closed',
  'Tsd Bellevarde': 'closed',
  'Tsd Borsat': 'closed',
  'Tsd Loyes': 'closed',
  'Tsd Marmottes': 'closed',
  'Ts Fontaine': 'closed',
  'Ts Grand Pre': 'closed',
  'Ts Mont Blanc': 'closed',
  'Tk Lanches': 'closed',
  'Tk Slalom': 'closed',
  'Tk Snowpark': 'closed',
  'Tapis Carpe Diem': 'closed',
  'Tph Fornet': 'closed',
  'Tc Vallon': 'closed',
  'Tsd Laisinant': 'closed',
  'Tsd Pyramides': 'closed',
  'Tk Col': 'closed',
  'Tk Signal': 'closed',
  'Tsd Cascades': 'closed',
  'Ts Cema': 'closed',
  'Tk Montets': 'closed',
  'Tk Pays Desert': 'closed',
  'Tc Solaise': 'closed',
  'Tsd Glacier': 'closed',
  'Tsd Leissieres': 'closed',
  'Tsd Madeleine': 'closed',
  'Tsd Manchet': 'closed',
  'Ts Cugnai': 'closed',
  'Ts Datcha': 'closed',
  'Ts Rogoney': 'closed',
  'Ts Village': 'closed',
  'Tk 3000': 'closed',
  'Tk Legettaz': 'closed',
  'Tk Savonette': 'closed',
  'Tapis Pim Pam': 'closed',
  'Tapis Poum': 'closed',
});
