const lifts = require('../lifts');

lifts('verbier', 'html', {
  'La Chaux - Gentianes (Jumbo)': 'open',
  'Tortin - Gentianes': 'open',
  'Gentianes': 'open',
  'Mont - Fort': 'open',
  'Le Châble - Verbier': 'open',
  'Verbier - Ruinettes': 'open',
  'Mayentzet': 'open',
  'La Chaux-Express': 'open',
  'Funispace': 'open',
  'Les Attelas': 'open',
  'La Chaux 2': 'open',
  'Lac des Vaux 1': 'open',
  'Lac des Vaux 2': 'open',
  'Chassoure': 'open',
  'Mont - Gelé': 'closed',
  'Les Esserts': 'open',
  'Les Moulins': 'open',
  'Le Rouge': 'open',
  'Verbier - Savoleyres': 'open',
  'Savoleyres Sud': 'open',
  'La Tournelle': 'open',
  'Tournelle': 'open',
  'La Tzoumaz - Savoleyres': 'open',
  'Tapis Tzoumaz': 'open',
  'Les Etablons': 'open',
  'Taillay': 'open',
  'Savoleyres Nord': 'open',
  'Le Châble - Mayens de Bruson': 'open',
  'Moay': 'open',
  'La Pasay': 'open',
  'Le Grand - Tsai': 'open'
});
